//
// Copyright (c) 2023 Dmitry Poroh
// All rights reserved.
// Distributed under the terms of the MIT License. See the LICENSE file.
//
// OpaqueString data object.
// It should be generated by your crypto provider
// For OpenSSL it corresponds to OSSL_SASLprep result
//

#pragma once

#include <string>
#include "util/util_tagged_type.hpp"

namespace freewebrtc::crypto {

struct OpaqueStringTag;
using OpaqueString = util::TaggedType<std::string, OpaqueStringTag>;

}
